{% set name = "darwin-py" %}
{% set version = "0.5.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/darwin-py-{{ version }}.tar.gz
  sha256: b7fc509034d66036016c6c6c9dd71f49e570bdc6ee40f517f5ab9ffa50bc2e4a

build:
  number: 1
  noarch: python
  entry_points:
    - darwin=darwin.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - argcomplete
    - dataclasses
    - humanize
    - numpy
    - pillow
    - python >={{ python_min }}
    - pyyaml >=5.1
    - requests
    - tqdm
    - upolygon ==0.1.6

test:
  imports:
    - darwin
    - darwin.dataset
    - darwin.exporter
    - darwin.importer

  commands:
    # disabled because upstream setup.py needs fixing https://github.com/v7labs/darwin-py/issues/144
    # - pip check
    - darwin --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/v7labs/darwin-py
  summary: Library and command line interface for darwin.v7labs.com
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hajapy
